services:
  kalender-opa:
    build: .
    container_name: kalender-opa
    env_file:
      - .env
    environment:
      PORT: "41773"
    ports:
      - "8082:41773"
    volumes:
      - kalender-opa-data:/data
    restart: unless-stopped

volumes:
  kalender-opa-data:
